version: '3.5'

services:
  nextjs:
      container_name: frontend
      build:
        context: .
        dockerfile: Dockerfile.frontend
      restart: always
      environment:
        - NODE_ENV=production
      ports:
        - 3000:3000
      networks:
        - starlink

  nginx:
    build: 
      context: .
      dockerfile: ./Dockerfile.nginx
    ports:
      - 80:80
    networks:
      - starlink

networks:
  starlink:
    name: starlink

