FROM node:20

WORKDIR /app

COPY package.json yarn.lock ./

# for working fast refetch on windows
ENV NODE_ENV=development
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

RUN yarn config set strict-ssl false
RUN yarn install --frozen-lockfile --verbose 

COPY . . 

CMD ["yarn", "dev"]