export default function Head() {
	return (
		<>
			<title>Create Next App</title>
			<meta content="width=device-width, initial-scale=1" name="viewport" />
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
			<meta
				name="keywords"
				content="Сейфы Промет, сейфы, купить сейф промет, металлическая мебель промет, купить шкаф промет, купить сейф в Москве,"
			></meta>
			<meta
				name="description"
				content="Сейфы Промет - в нашем специализированном интернет-магазине представлена вся линейка продукции «Промет» - сейфы и металлическая мебель любых размеров, с серьезной степенью защиты."
			></meta>
			<title>Промет — сейфы и металлическая мебель купить в Москве</title>
		</>
	)
}
