FROM node:20
WORKDIR /app

RUN yarn global add pm2

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build

EXPOSE 3000

USER node

CMD [ "pm2-runtime", "npm", "--", "start" ]